# Generated by Django 5.1.3 on 2024-11-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
