# Generated by Django 5.1.3 on 2024-11-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userregistration_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='reset_token',
        ),
    ]
